### PR TITLE
FRONTEND: add in missing dev dependencies for jest

### PR DESCRIPTION
**Pull request by cviveiro**
adds in dependencies that were missing from #123. noticed on https://github.com/MetLifeLegalPlans/document-generation/pull/24.

tested with the docgen repo.

### CODE REVIEW

**Review by markrawls — CHANGES_REQUESTED** [review]
Make sure to rebase and choose a new version number, then we can merge this

**Comment by cviveiro** [comment]
done

**Comment by cviveiro** [comment]
Not sure what's behind the test failure especially since it had passed before?
```
2/4] Fetching packages...
error postcss@8.1.1: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14". Got "13.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom next --cwd /home/runner/work/zygoat/zygoat/frontend has failed.

Done in 15.23s.
INFO => Emptying a poorly formatted index.js file
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.7/site-packages/zygoat/components/base.py", line 156, in _run_self
    phase_func()
  File "/home/runner/.local/lib/python3.7/site-packages/zygoat/components/frontend/__init__.py", line 31, in create
    open(os.path.join(Projects.FRONTEND, "pages", "index.js"), "w").close()
FileNotFoundError: [Errno 2] No such file or directory: 'frontend/pages/index.js'
Error: Process completed with exit code 1.
```

**Comment by markrawls** [comment]
`error postcss@8.1.1: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14". Got "13.14.0"`

So for some reason a dependency of  `create-next-app` has stopped supporting node `13` as of like today. You'll need to change the version installed in the workflow file.

**Review by markrawls — APPROVED** [review]

**Pull request merged**
