### PR TITLE
APP: import React

### PR DESCRIPTION
**Pull request by kborer**
Had to do this to get a newly initialized, vanilla zygoat app to run. Maybe I'm missing something.

### CODE REVIEW

**Comment by cviveiro** [comment]
ah it does look like it's used below. lgtm but i think the version number should get upped before this gets merged

looks like doc gen doesn't have this, nor does the new digex repo. they should get updated too.

**Review by markrawls — DISMISSED** [review]
Increment the version number (patch) first, then we'll get it merged and deployed

**Comment by kborer** [comment]
bumped

**Review by markrawls — APPROVED** [review]

**Comment by markrawls** [comment]
@kborer You'll need to change the node version in the tests file to `14` - some dependency of `create-next-app` dropped support for Node 13 for some reason.

**Review by cviveiro — APPROVED** [review]

**Comment by cviveiro** [comment]
oh wait, version number i think is missing

**Comment by markrawls** [comment]
Whoops, good catch. Updated!

**Review by cviveiro — APPROVED** [review]
ok now actually lgtm

**Pull request merged**
